# -*- coding: utf-8 -*-
"""iterate over a dictionary using for loop and print the key alone ,value alone and both key and value alone  .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13oGHdnG_AgoNlLfWN-PnfUESWLNiYqWq
"""

#write a program to iterate over a dictionary using for loop and print the key alone ,value alone and both key and value alone 
data = {'a': 'apple', 'b': 'doll', 'c': 'cat','d': 'dog'}


print('iterating for keys')
for key in data:
    print(key)

print('iterating for values')
for value in data.values():
    print(value)

print('iterating for kays and values') 
for key in data:
    print(key,data[key])

