# -*- coding: utf-8 -*-
"""write a program to prepare a dictionary where the keys are number between 1 and 15 and values are square of the keys.ipyb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13oGHdnG_AgoNlLfWN-PnfUESWLNiYqWq
"""

#write a program to prepare a dictionary where the keys are number between 1 and 15 and values are square of the keys
d=dict()
for x in range(1,16):
    d[x]=x**2
print(d)

