# -*- coding: utf-8 -*-
"""write a program to concatenate the following dictionaries to create a new one  .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13oGHdnG_AgoNlLfWN-PnfUESWLNiYqWq
"""

#write a program to concatenate the following dictionaries to create a new one 
dict1={1:10,2:20}
dict2={3:30,4:40}
dict3={5:50,6:60}
dict1.update(dict2)
dict1.update(dict3)
dict1

