# -*- coding: utf-8 -*-
"""write a program to add a key and a value to a dictionary .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13oGHdnG_AgoNlLfWN-PnfUESWLNiYqWq
"""

#write a program to add a key and a value to a dictionary 

sample_Dictionary={0:10,1:20}
sample_Dictionary.update({2:30})
sample_Dictionary

