# -*- coding: utf-8 -*-
"""write a program to check the given key already present in the dictionary .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13oGHdnG_AgoNlLfWN-PnfUESWLNiYqWq
"""

#write a program to check the given key already present in the dictionary
d={'A':1,'B':2,'C':3}
key=input("Enter key to check:")
if key in d.keys():
      print("Key is present and value of the key is:")
      print(d[key])
else:
      print("Key isn't present!")

