# -*- coding: utf-8 -*-
"""write a program to add all the values in the dictionary, considering the value will be of int type

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13oGHdnG_AgoNlLfWN-PnfUESWLNiYqWq
"""

#write a program to add all the values in the dictionary, considering the value will be of int type
my_dict = {'a':102,'b':501,'c':112}
print(sum(my_dict.values()))

