# -*- coding: utf-8 -*-
"""write a program to convert a list into tuple

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13oGHdnG_AgoNlLfWN-PnfUESWLNiYqWq
"""

#write a program to remove a given item from the set
#Create a new set
num_set = set([0, 1, 2, 3, 4, 5])
a=int(input('enter the element want to remove:-'))
if a in num_set:
  num_set.discard(a)
print("after removing element:-",num_set)

