# -*- coding: utf-8 -*-
"""write a program to convert a list into tuple

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13oGHdnG_AgoNlLfWN-PnfUESWLNiYqWq
"""

#write a program to find maximum and the minimum of the set
#Create a set
setn = {5, 10, 3, 15, 2, 20}
print("Original set elements:")
print(setn)
print(type(setn))
print("\nMaximum value of the said set:")
print(max(setn))
print("\nMinimum value of the said set:")
print(min(setn))

