# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gdHdCzDZjVqNd2Sfl6onJs3mgPmo32wW
"""

#write a function to return thre factorial of a number(a non-negative number)
def factorial(n):   
    if n == 0:
        return 1    
    return n * factorial(n-1)
  

num = 5;
print("Factorial of", num, "is",
factorial(num))