# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gdHdCzDZjVqNd2Sfl6onJs3mgPmo32wW
"""

#write a function to print even number from a givern list.
def check_for_even_odd(a):
  even=[]
  odd=[]
  for i in a:
    if i%2==0:
      even.append(i)
    else:
      odd.append(i)
  print('the even numbers in the list are:-',even,'\nthe odd numbers in the list are:-',odd)

if __name__=='__main__':
  a=[1,2,3,4,5,6,7,8,9,10]
  check_for_even_odd(a)