# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gdHdCzDZjVqNd2Sfl6onJs3mgPmo32wW
"""

#write a function that accepts a string and prints the number of upper and lower case letter in it.
def check_for_uppercase_and_lowercase(a):
  upper=0
  lower=0
  for i in a:
        if(i.islower()):
              upper=upper+1
        elif(i.isupper()):
          lower=lower+1
  print('uppercase letters are:-',upper,'\nlowercase letters are:-',lower)

if __name__=='__main__':
  a="Hello how are you.Hope you are doing well"
  print(check_for_uppercase_and_lowercase(a))