# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gdHdCzDZjVqNd2Sfl6onJs3mgPmo32wW
"""

#write a function which takes a number into parameter and checks weather it is prime or not.

def check_for_prime(num):
  if num > 1:
      for i in range(2, int(num/2)+1):
          if (num % i) == 0:
              print(num, "is not a prime number")
              break
      else:
          print(num, "is a prime number")   
  else:
      print(num, "is not a prime number")


if __name__=='__main__':
  num=11
  check_for_prime(num)