# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gdHdCzDZjVqNd2Sfl6onJs3mgPmo32wW
"""

#write a function to return the revese of the string
def reverse_the_string(a):
  print("before reversing:-",a)
  b="\nafter reversing:-"
  c=a[::-1]
  return b,c

if __name__=='__main__':
  a="123abcd"
  print(reverse_the_string(a))