# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gdHdCzDZjVqNd2Sfl6onJs3mgPmo32wW
"""

#write a program to return sum of all the numbers in the string

def sum_of_all_numbers(a):
  sum=0
  for i in a:
    sum=sum+i
  return sum

if __name__=='__main__':
  a=[8,2,3,0,7]
  function=sum_of_all_numbers(a)
  print(function)