# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cK-lk0bszIHhM631_8kTbkSM9GsUTIV8
"""

#Write a program to accept a welcome message through command line arguments and display the file name along with the welcome message.
import sys
with open(sys.argv[1]) as filename:
        for line in filename:
               print(line)