# -*- coding: utf-8 -*-
"""write a program to create a list of 5 intergers and display the list items.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13oGHdnG_AgoNlLfWN-PnfUESWLNiYqWq
"""

#write a program to create a list of 5 intergers and display the list items. Access individual elements through index

list1=[1,2,3,4,5]
for i in list1:
  print(i,end=" ")

#access the list individually
print('\n access the list individually')
print(list1[0])
print(list1[1])
print(list1[2])
print(list1[3])
print(list1[4])

