# -*- coding: utf-8 -*-
"""write aprogram to append a new item to the end of the list .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13oGHdnG_AgoNlLfWN-PnfUESWLNiYqWq
"""

#write aprogram to append a new item to the end of the list 

list2=[1,2,3,4,5]

list2.append(6)

print('after apppending 6 in list2 we will get',list2)

