# -*- coding: utf-8 -*-
"""write a program to remove the element from a specified index .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13oGHdnG_AgoNlLfWN-PnfUESWLNiYqWq
"""

#write a program to remove the element from a specified index
list8=[1,2,3,4,5,6]

a=int(input('enter the specified index'))
list8.remove(list8[a])
list8

