# -*- coding: utf-8 -*-
"""write a program to insert a new item before the second element in the existing list .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13oGHdnG_AgoNlLfWN-PnfUESWLNiYqWq
"""

#write a program to insert a new item before the second element in the existing list 

list7=[1,2,3,4,5,6]
list7.insert(1, 7)
list7

