# -*- coding: utf-8 -*-
"""write a program to append items from list1 to list 2  in the front  .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13oGHdnG_AgoNlLfWN-PnfUESWLNiYqWq
"""

#write a program to append items from list1 to list 2  in the front 


list5=[1,2,3,4,5]
list6=[6,7,8,9]
print("after appending in the front th list will look like something like this ",list6+list5)

