# -*- coding: utf-8 -*-
"""write a program to reverse the order of the items in the list .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13oGHdnG_AgoNlLfWN-PnfUESWLNiYqWq
"""

#write a program to reverse the order of the items in the list

fruits = ['apple', 'banana', 'cherry']

fruits.reverse()

print(fruits)

