# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cK-lk0bszIHhM631_8kTbkSM9GsUTIV8
"""

# write a program to read the content of a txt file line by line and store the each line into the each list.
with open("wipro_python_fundamentals.txt") as file_in:
    lines = []
    for line in file_in:
        lines.append(line.strip('\n'))
    print(lines)