# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cK-lk0bszIHhM631_8kTbkSM9GsUTIV8
"""

#write aprogram to take input from the user and append it into the txt file 
input=input('enter the line :-')
file1 = open("myfile.txt", "a")  
file1.write(input)
file1.close()