# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cK-lk0bszIHhM631_8kTbkSM9GsUTIV8
"""

#declare a list with 10 integers and ask the user to enter an index. Check whether the number in that index is positive or negative number. If any invalid index is entered, handle the exception and print an error message.

num=[1,-2,3,4,5,6,7,8,9,10]
a=int(input('enter the index'))
index=num[a]
try:
  if index>0:
    print('the number is positive:-',index)
  else:
    print('the number is negative')
except:
  print('number is negative')