# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cK-lk0bszIHhM631_8kTbkSM9GsUTIV8
"""

#Write a program to accept two numbers from the user and perform division. If any exception occurs, print an error message or else print the result.
try:
    a=int(input('enter the first number:-'))
    b=int(input('enter the second number:-'))
    c=a/b
    print('divions of two numbers resulted:-',c)
except:
    print('Some error occurred.')
print("Out of try except blocks.")