# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DWoxYoywrECTD7spEiqsMW6Dz6aPqD6Q
"""

#given a string, if the first or last charecter is x , return the string without those x.
a='xHix'
if a[0] and a[-1] is 'x':
  print(a[1:-1])