# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DWoxYoywrECTD7spEiqsMW6Dz6aPqD6Q
"""

#given a string and an integer n, return a string made of n last n charecters of the string.
a='wipro'
b=len(a)
a=a[-2:]
print('the desired output is:-',a*b)