# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DWoxYoywrECTD7spEiqsMW6Dz6aPqD6Q
"""

#given a string , return a new string made of n copies ofthe first 2 char of original string.....
a='wipro'
b=len(a)
a=a[0:2]
print('the desired output is:-',a*b)