# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DWoxYoywrECTD7spEiqsMW6Dz6aPqD6Q
"""

# write a program that will check weather given string palindrome or not

# function which return reverse of a string
 
def isPalindrome(s):
    return s == s[::-1]
 
 
# Driver code
s = "abbbba"
ans = isPalindrome(s)
 
if ans:
    print("Yes")
else:
    print("No")