# -*- coding: utf-8 -*-
"""write a program to convert a list into tuple

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13oGHdnG_AgoNlLfWN-PnfUESWLNiYqWq
"""

#write a program to replace last value of tuples in a list to 100
tuple2=[(10,20,30),(40,50,60),(70,80,90)]
print([t[:-1] + (100,) for t in tuple2])

