# -*- coding: utf-8 -*-
"""write a program to print the 4th element from the last in a tuple.

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13oGHdnG_AgoNlLfWN-PnfUESWLNiYqWq
"""

#write a program to check weather the element exist int he tuple or not

tuplex = ("w",  "r", "e", "s", "o", "u", "r", "c", "e")
a=input('enter the value to check:-')

if a in tuplex:
  print('yes value is present')
else:
  print('value is not present')

