# -*- coding: utf-8 -*-
"""write a program to print the 4th element from the last in a tuple.

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13oGHdnG_AgoNlLfWN-PnfUESWLNiYqWq
"""

#write a program to print the 4th element from the last in a tuple.

#Get an item of the tuple
tuplex = ("w", 3, "r", "e", "s", "o", "u", "r", "c", "e")
print(tuplex)
#Get item (4th element from last)
item1 = tuplex[-4]
print(item1)

