# -*- coding: utf-8 -*-
"""write a program to convert a list into tuple

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13oGHdnG_AgoNlLfWN-PnfUESWLNiYqWq
"""

#write a program to convert a list into tuple
list1=[24 ,26 ,28 ,30 ,32 ,34 ,36 ,38 ,40 ,42 ,44 ,46 ,48 ,50 ,52 ,54 ,56]
tuple2=tuple(list1)

print("converted tuple is :-",tuple2)

